var markers = [
  {
    country: 'United States',
    institution: 'LSU Museum of Natural Science',
    name: ' Dr. Prosanta Chakrabarty',
    email: 'prosanta@lsu.edu',
    description: 'Permits; Logistics; Resources',
    url: 'https://www.lsu.edu/mns/',
    field: 'Icthyology',
    img: './img2/us.png',
    lat: 30.4153223689966,
    lng: -91.18000122437911,
  },
    {
    country: 'United States',
    institution: 'LSU Museum of Natural Science',
    name: ' Dr. Gregory Thom',
    email: 'prosanta@lsu.edu',
    description: 'Permits; Logistics; Resources',
    url: 'https://www.lsu.edu/mns/',
    field: 'Ornithology',
    img: './img2/us.png',
    lat: 30.6,
    lng: -91.6,
  },
    {
    country: 'United States',
    institution: 'UC Berkeley Museum of Vertebrate Zoology',
    name: ' Dr. Rebecca Tarvin',
    email: 'rdtarvin@berkeley.edu',
    description: 'Permits; Logistics; Resources',
    url: 'https://ib.berkeley.edu/people/faculty/tarvinr',
    field: 'Herpethology',
    img: './img2/us.png',
    lat: 37.8715169567739, 
    lng: -122.26193696746348,
  },
     {
    country: 'United States',
    institution: 'Department of Biology, UTA',
    name: ' Dr. Janet Buckner',
    email: 'jcbuckner1@gmail.com',
    description: 'Permits; Logistics; Resources',
    url: 'https://www.iderlab.org/',
    field: 'Herpethology',
    img: './img2/us.png',
    lat: 32.72910337522349, 
    lng: -97.11497179685189,
  },
     {
    country: 'Haiti',
    institution: 'Université Chrétienne du Nord d`Haïti - UCNH',
    name: ' Na',
    email: 'Na',
    description: 'Permits; Logistics; Resources',
    url: 'Na',
    field: 'Herpethology',
    img: './img2/ha.png',
    lat: 19.74595623595172,
    lng: -72.36941424634756,
  },
    {
    country: 'Brazil',
    institution: 'Instituto de Pesquisas Ambientais da Amazonia - INPA',
    name: ' Na',
    email: 'Na',
    description: 'Permits; Logistics; Resources',
    url: 'Na',
    field: 'Ornithology',
    img: './img2/br.png',
    lat: -3.095569532153714, 
    lng: -59.99011552274308,
  },
    {
    country: 'Argentina',
    institution: 'Museo Argentino de Ciencias Naturales "Bernardino Rivadavia"',
    name: ' Na',
    email: 'Na',
    description: 'Permits; Logistics; Resources',
    url: 'Na',
    field: 'Ornithology',
    img: './img2/ar.png',
    lat: -34.606049309674795, 
    lng: -58.43788519821982,
  },
    {
    country: 'Colombia',
    institution: 'Alexander Von Humboldt Institute',
    name: ' Na',
    email: 'Na',
    description: 'Permits; Logistics; Resources',
    url: 'Na',
    field: 'Ornithology',
    img: './img2/co.png',
    lat: 4.870593938278141, 
    lng: -74.02893355763845,
  },
]





